// Build data/library.json and data/sdf/*.sdf from data/seed.ts.
//
// For every seed entry: parse the expected formula, ask PubChem for the
// compound by name (or CID), keep the first hit whose formula agrees with
// the seed (a wrong hit is printed and skipped, never stored), fetch the
// CAS number from the synonym list, and store a 3D structure: PubChem's
// conformer when it has one, otherwise one generated by OpenChemLib.
//
//   node scripts/build-library.ts              full build (cached, so reruns are fast)
//   node scripts/build-library.ts --only water  one entry, by name
//   node scripts/build-library.ts --no-cas      skip the synonym requests

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { SEED, type SeedEntry } from '../data/seed.ts';
import { molarMass, parseFormula } from '../src/chem/formula.ts';
import { LIBRARY_FILE, SDF_DIR } from '../src/chem/paths.ts';
import { findCas, pubchem, type PubChemCompound } from '../src/chem/pubchem.ts';
import { smilesCharge, smilesToMolfile3D } from '../src/chem/structure.ts';
import type { LibraryEntry, LibraryFile } from '../src/chem/types.ts';

const args = process.argv.slice(2);
const only = args.includes('--only') ? args[args.indexOf('--only') + 1]?.toLowerCase() : null;
const withCas = !args.includes('--no-cas');

export function slugify(name: string): string {
  return name
    .normalize('NFKD')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function hillOf(formula: string): string | null {
  try {
    return parseFormula(formula, { lenient: false }).hill;
  } catch {
    return null;
  }
}

interface Outcome {
  seed: SeedEntry;
  entry?: LibraryEntry;
  problem?: string;
}

async function lookup(seed: SeedEntry): Promise<PubChemCompound[]> {
  if (seed.cid) {
    const hit = await pubchem.byCid(seed.cid);
    return hit ? [hit] : [];
  }
  const names = [seed.pubchemName ?? seed.name, ...(seed.pubchemName ? [seed.name] : []), ...(seed.aliases ?? [])];
  for (const name of names) {
    const hits = await pubchem.byName(name);
    if (hits.length) return hits;
  }
  return [];
}

async function build(seed: SeedEntry, rank: number, id: string): Promise<Outcome> {
  const expected = hillOf(seed.formula);
  if (!expected) return { seed, problem: `formula "${seed.formula}" does not parse` };
  const counts = parseFormula(seed.formula, { lenient: false }).counts;

  let hits: PubChemCompound[];
  try {
    hits = await lookup(seed);
  } catch (err) {
    return { seed, problem: `PubChem error: ${err instanceof Error ? err.message : String(err)}` };
  }
  if (hits.length === 0) return { seed, problem: 'PubChem knows no such name' };
  const hit = hits.find((h) => hillOf(h.formula) === expected);
  if (!hit) {
    return { seed, problem: `formula mismatch: seed ${expected}, PubChem ${hits.map((h) => `${h.formula} (CID ${h.cid}, ${h.title})`).join('; ')}` };
  }

  let cas: string | undefined;
  if (withCas) {
    try {
      cas = findCas(await pubchem.synonyms(hit.cid));
    } catch {
      cas = undefined;
    }
  }

  let sdf: string | null = null;
  let sdfSource: LibraryEntry['sdfSource'] = 'none';
  try {
    sdf = await pubchem.sdf(hit.cid, '3d');
    if (sdf) sdfSource = 'pubchem3d';
  } catch {
    sdf = null;
  }
  if (!sdf && hit.smiles) {
    sdf = smilesToMolfile3D(hit.smiles);
    if (sdf) sdfSource = 'ocl';
  }
  if (sdf) await writeFile(path.join(SDF_DIR, `${id}.sdf`), sdf);

  const entry: LibraryEntry = {
    id,
    name: seed.name,
    formula: seed.formula,
    hill: expected,
    aliases: [...new Set((seed.aliases ?? []).map((a) => a.trim()).filter(Boolean))],
    category: seed.category,
    tags: seed.tags ?? [],
    note: seed.note ?? '',
    kind: seed.kind ?? 'molecule',
    smiles: hit.smiles,
    iupac: hit.iupac,
    cid: hit.cid,
    cas,
    molarMass: Math.round(molarMass(counts) * 1000) / 1000,
    charge: smilesCharge(hit.smiles),
    sdfSource,
    rank,
  };
  return { seed, entry };
}

async function main(): Promise<void> {
  await mkdir(SDF_DIR, { recursive: true });
  const ids = new Set<string>();
  const jobs: Array<{ seed: SeedEntry; rank: number; id: string }> = [];
  SEED.forEach((seed, rank) => {
    if (only && seed.name.toLowerCase() !== only) return;
    let id = slugify(seed.name);
    let n = 2;
    while (ids.has(id)) id = `${slugify(seed.name)}-${n++}`;
    ids.add(id);
    jobs.push({ seed, rank, id });
  });

  const outcomes: Outcome[] = [];
  const started = Date.now();
  const chunk = 6;
  for (let i = 0; i < jobs.length; i += chunk) {
    const batch = jobs.slice(i, i + chunk);
    const results = await Promise.all(batch.map((j) => build(j.seed, j.rank, j.id)));
    outcomes.push(...results);
    const done = Math.min(i + chunk, jobs.length);
    const ok = outcomes.filter((o) => o.entry).length;
    process.stdout.write(`\r${done}/${jobs.length} looked up, ${ok} stored, ${Math.round((Date.now() - started) / 1000)}s`);
  }
  process.stdout.write('\n');

  const entries = outcomes.filter((o) => o.entry).map((o) => o.entry!);
  const problems = outcomes.filter((o) => o.problem);
  for (const p of problems) console.log(`SKIPPED  ${p.seed.name.padEnd(36)} ${p.problem}`);

  const bySource = entries.reduce<Record<string, number>>((acc, e) => ({ ...acc, [e.sdfSource]: (acc[e.sdfSource] ?? 0) + 1 }), {});
  console.log(`\n${entries.length} entries written, ${problems.length} skipped. 3D sources: ${JSON.stringify(bySource)}`);

  if (only) {
    console.log(JSON.stringify(entries, null, 2));
    return;
  }
  const file: LibraryFile = { generatedAt: new Date().toISOString(), entries };
  await writeFile(LIBRARY_FILE, JSON.stringify(file, null, 1));
  console.log(`wrote ${LIBRARY_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
