// ─────────────────────────────────────────────────────────────────────────
// Live, locally-rendered Typst preview.
//
// Debounces the source, compiles it to SVG in-browser (see lib/typst-compiler)
// and shows the rendered pages. Compile errors surface as a banner with the
// Typst diagnostics (file:line ranges) while the last good render stays
// visible, so a transient typo doesn't blank the preview.
//
// Pages are mounted individually and lazily (see `PageCard`). typst.ts
// renders the whole document into one <svg>; for a long report that is tens
// of thousands of nodes (a <use> per glyph, a position:fixed <div> per text
// run), and committing all of it after every keystroke pause cost seconds of
// style/layout/paint on the main thread while the compile itself took tens
// of milliseconds. Splitting the SVG per page (lib/typst-pages) lets the
// preview keep only the pages near the viewport in the DOM, and leave a
// page's DOM untouched when its markup did not change between compiles.
// ─────────────────────────────────────────────────────────────────────────

import { useEffect, useLayoutEffect, useRef, useState, useCallback, useMemo, memo, type RefObject } from 'react';
import { ZoomIn, ZoomOut, Maximize, Loader2, AlertTriangle } from 'lucide-react';
import { compileTypstSvg, typstErrorMessage, type TypstDiagnostic } from '@/lib/typst-compiler';
import { splitTypstPages, extractTextRuns, reconcileDefs, splitSharedStyle, DEFAULT_PAGE_GAP, type SplitTypstSvg } from '@/lib/typst-pages';
import { occurrenceIndex } from '@/lib/typst-source-map';
import { renderCache } from '@/lib/workspace-cache';
import { switchTrace } from '@/lib/perf';

/** One guess at what a preview click corresponds to in the source. */
export interface SourceCandidate {
  text: string;
  occurrence: number;
}

/**
 * A rendered run that Typst generated rather than the author typing it:
 * a heading number, a figure counter. These have no source text to jump to,
 * so they're tried *after* their neighbours.
 *
 * Deliberately narrow: a short run of digits and dots. Real content that
 * looks numeric (an IP like `10.0.0.5`, a CVSS score in a table) stays a
 * first-class candidate.
 */
function looksAutoGenerated(text: string): boolean {
  return /^[\d.]{1,4}$/.test(text.trim());
}

/**
 * Resolve a click to ordered source candidates, best guess first.
 *
 * typst.ts emits a hidden selection layer: one `<foreignObject>` per text
 * run, containing a `.tsel` div with the literal characters. We hit-test
 * against those boxes geometrically rather than trusting `event.target`,
 * because the `.tsel` divs are `position: fixed` (typst.ts's trick for making
 * text selectable across the SVG), so whatever the browser reports as the
 * event target isn't reliably the run under the cursor.
 *
 * Falls back to the nearest box when the click lands in a margin or between
 * lines, so clicking roughly at something still works.
 *
 * `precedingTexts` are the runs of every page before `container`'s, in
 * order: an occurrence index only means something counted from the start of
 * the document, and `container` is a single page.
 */
function textRunAtPoint(
  container: HTMLElement,
  clientX: number,
  clientY: number,
  precedingTexts: readonly string[] = [],
): SourceCandidate[] {
  const objects = Array.from(container.querySelectorAll('foreignObject'));
  if (objects.length === 0) return [];

  const texts = objects.map((o) => o.textContent ?? '');

  let bestIndex = -1;
  let bestDistance = Infinity;
  for (let i = 0; i < objects.length; i++) {
    if (!texts[i]!.trim()) continue;
    const r = objects[i]!.getBoundingClientRect();
    if (r.width === 0 && r.height === 0) continue;

    // Distance to the box: zero when the point is inside it.
    const dx = Math.max(r.left - clientX, 0, clientX - r.right);
    const dy = Math.max(r.top - clientY, 0, clientY - r.bottom);
    const distance = Math.hypot(dx, dy);
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = i;
      if (distance === 0) break; // inside a run: can't do better
    }
  }

  if (bestIndex === -1) return [];
  // Ignore a click far from any text (empty page area) rather than yanking
  // the cursor to something arbitrary.
  if (bestDistance > 120) return [];

  // Offer the neighbours as fallbacks. Clicking a heading's number should
  // land on the heading, and a run whose text Typst transformed beyond
  // recognition shouldn't dead-end when the run beside it would resolve.
  const order = [bestIndex, bestIndex + 1, bestIndex - 1, bestIndex + 2];
  if (looksAutoGenerated(texts[bestIndex]!)) {
    // A counter has no source of its own: prefer the content it labels.
    order.splice(0, 1);
    order.push(bestIndex);
  }

  const allTexts = precedingTexts.length > 0 ? [...precedingTexts, ...texts] : texts;
  const offset = precedingTexts.length;
  const seen = new Set<number>();
  const candidates: SourceCandidate[] = [];
  for (const i of order) {
    if (i < 0 || i >= texts.length || seen.has(i)) continue;
    seen.add(i);
    if (!texts[i]!.trim()) continue;
    candidates.push({ text: texts[i]!, occurrence: occurrenceIndex(allTexts, offset + i) });
  }
  return candidates;
}

/** The data-URI href of the rendered image under the pointer, if any. */
function imageHrefAtPoint(
  container: HTMLElement,
  clientX: number,
  clientY: number,
): string | null {
  let best: { href: string; area: number } | null = null;
  for (const img of Array.from(container.querySelectorAll('svg image'))) {
    const r = img.getBoundingClientRect();
    if (clientX < r.left || clientX > r.right || clientY < r.top || clientY > r.bottom) continue;
    const href = img.getAttribute('href') || img.getAttribute('xlink:href');
    if (!href) continue;
    const area = r.width * r.height;
    // Prefer the smallest hit: a figure nested over a full-page background
    // image should win over the background.
    if (!best || area < best.area) best = { href, area };
  }
  return best?.href ?? null;
}

const DEBOUNCE_MS = 350;
const MIN_ZOOM = 0.25;
const MAX_ZOOM = 3;

/**
 * Pages mounted on first render without waiting for the observer: the
 * preview opens scrolled to the top, and a frame of empty cards there would
 * flash on every workspace switch.
 */
const EAGER_PAGES = 2;

/**
 * How far beyond the scroll viewport a page is kept mounted, as a multiple of
 * the viewport height on each side. Generous enough that ordinary scrolling
 * never reaches an empty card, small enough that a long report keeps only a
 * handful of pages in the DOM.
 */
const MOUNT_MARGIN = '150% 0px';

const SVG_NS = 'http://www.w3.org/2000/svg';

/**
 * typst.ts's stylesheet. It is the same text for every compile, and React
 * leaves a <style> alone while its text is unchanged, so the document's
 * styles are never invalidated by a compile (which, with a long report on
 * screen, costs a full second of style recalculation).
 */
const SharedStyle = memo(function SharedStyle({ css }: { css: string }) {
  return <style>{css}</style>;
});

/**
 * The glyph/clip-path <defs>, mounted once in a zero-size <svg>. Every
 * page's `<use href="#…">` resolves against the document, so the defs need
 * to exist exactly once, anywhere in it. Not `display: none`: a referenced
 * element inside a display:none subtree may still render through <use>, but
 * paint servers and clip paths are safer with the subtree merely hidden by
 * size. Updated by `reconcileDefs`, so a glyph still in use keeps its node.
 */
const SharedDefs = memo(function SharedDefs({ markup }: { markup: string }) {
  const ref = useRef<SVGSVGElement>(null);
  useLayoutEffect(() => { if (ref.current) reconcileDefs(ref.current, markup); }, [markup]);
  return (
    <svg
      ref={ref}
      xmlns={SVG_NS}
      aria-hidden="true"
      style={{ position: 'absolute', width: 0, height: 0, overflow: 'hidden' }}
    />
  );
});

/**
 * One page: a white card of the page's exact size, whose SVG content is
 * mounted only while the card is within `MOUNT_MARGIN` of the scroll
 * viewport. Memoized on the fragment, so a compile that left this page's
 * markup unchanged never touches its DOM.
 */
const PageCard = memo(function PageCard({
  tid,
  width,
  height,
  body,
  index,
  scrollRoot,
}: {
  tid: string;
  width: number;
  height: number;
  body: string;
  index: number;
  scrollRoot: RefObject<HTMLDivElement | null>;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [near, setNear] = useState(index < EAGER_PAGES);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (typeof IntersectionObserver === 'undefined') { setNear(true); return; }
    const observer = new IntersectionObserver(
      (entries) => { const entry = entries[entries.length - 1]; if (entry) setNear(entry.isIntersecting); },
      { root: scrollRoot.current, rootMargin: MOUNT_MARGIN },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [scrollRoot]);

  return (
    <div
      ref={ref}
      data-page-index={index}
      className="rounded-sm bg-white shadow-lg"
      // `content-visibility: auto`: a mounted page that has scrolled out of
      // view costs nothing in style and layout passes; its size is explicit,
      // so skipping it moves nothing.
      style={{ width: `${width}px`, height: `${height}px`, contain: 'layout', contentVisibility: 'auto', containIntrinsicSize: `${width}px ${height}px` }}
    >
      {near && (
        <svg
          xmlns={SVG_NS}
          className="block"
          viewBox={`0 0 ${width} ${height}`}
          width={width}
          height={height}
          data-tid={tid}
          dangerouslySetInnerHTML={{ __html: body }}
        />
      )}
    </div>
  );
});

/**
 * The page card the click belongs to: the one containing the event target,
 * else (a click in the gap between pages) the nearest one vertically.
 */
function pageCardAt(host: HTMLElement, target: Element | null, clientY: number): HTMLElement | null {
  const own = target?.closest<HTMLElement>('[data-page-index]');
  if (own) return own;
  let best: HTMLElement | null = null;
  let bestDistance = Infinity;
  for (const card of Array.from(host.querySelectorAll<HTMLElement>('[data-page-index]'))) {
    const r = card.getBoundingClientRect();
    const distance = Math.max(r.top - clientY, 0, clientY - r.bottom);
    if (distance < bestDistance) { bestDistance = distance; best = card; }
  }
  return best;
}

/** What the preview shows for one document: its last good render. */
interface DocRender {
  key: string;
  svg: string;
  diagnostics: TypstDiagnostic[];
  /** Scroll offset to restore once the pages are mounted; consumed once. */
  restoreScroll: number | null;
}

/** The starting state for a document: its cached render, or nothing yet. */
function docFromCache(key: string): DocRender {
  const snap = renderCache.get(key);
  return { key, svg: snap?.svg ?? '', diagnostics: snap?.diagnostics ?? [], restoreScroll: snap ? snap.scrollTop : null };
}

// Memoized so it only re-renders when `source` (or the asset revision)
// actually changes: in particular it is skipped entirely while the user
// drags the editor/preview divider (which only changes the parent's width
// state).
//
// `revision` bumps whenever the workspace's images/fonts change. It isn't
// used in the render, only as a compile trigger: a crop or a new screenshot
// changes what the *same* source renders to.
export const TypstPreview = memo(function TypstPreview({
  source,
  revision = 0,
  mainPath = '/main.typ',
  docKey = 'doc',
  ready = true,
  onRevealSource,
  onRevealImage,
}: {
  source: string;
  revision?: number;
  /**
   * Identifies the document (`workspace:file`). A change means a switch: the
   * outgoing render is kept in `renderCache`, the incoming document's cached
   * render (if any) is shown at once, and the first compile runs without the
   * typing debounce.
   */
  docKey?: string;
  /**
   * False while the document's text or mounted files are still arriving. No
   * compile runs until it is true, so a switch never renders the previous
   * text under the new path or a document with its images missing.
   */
  ready?: boolean;
  /**
   * Where `source` is mounted in the compiler's virtual filesystem: the
   * workspace-relative path of the file open in the editor, so a document
   * that `#include`s its neighbours resolves them from the right directory.
   */
  mainPath?: string;
  /**
   * Click-to-source. Receives ordered candidates (best guess first, then
   * neighbouring runs); the handler takes the first that resolves.
   */
  onRevealSource?: (candidates: SourceCandidate[]) => void;
  /**
   * Click-to-asset: fires instead of click-to-source when the click lands
   * on a rendered image, with that `<image>`'s (data URI) href.
   */
  onRevealImage?: (href: string) => void;
}) {
  const [doc, setDoc] = useState<DocRender>(() => docFromCache(docKey));
  const [fatalError, setFatalError] = useState<string | null>(null);
  const [firstLoad, setFirstLoad] = useState(true);
  const [compiling, setCompiling] = useState(false);
  const [zoom, setZoom] = useState(1);
  const pageAreaRef = useRef<HTMLDivElement>(null);
  // Where the user scrolled to, read without a layout query at switch time.
  const scrollTopRef = useRef(0);

  // A different document: remember what the outgoing one looked like and
  // show the incoming one's last render right away (derived state, so no
  // frame ever shows the old pages under the new key). Saving here rather
  // than in an effect keeps the scroll offset that belonged to the old pages.
  if (doc.key !== docKey) {
    if (doc.svg) renderCache.set(doc.key, { svg: doc.svg, diagnostics: doc.diagnostics, scrollTop: scrollTopRef.current });
    setDoc(docFromCache(docKey));
  }
  const shown = doc.key === docKey ? doc : docFromCache(docKey);
  const { svg, diagnostics } = shown;

  // Monotonic id so a slow compile that finishes after a newer one can't
  // overwrite the fresher result.
  const runId = useRef(0);
  // The document the last dispatched compile was for: a new one compiles at
  // once, the same one waits out the typing debounce.
  const compiledKey = useRef<string | null>(null);

  useEffect(() => {
    if (!ready) return;
    const id = ++runId.current;
    setCompiling(true);
    const immediate = compiledKey.current !== docKey;
    const timer = setTimeout(() => {
      compiledKey.current = docKey;
      switchTrace.mark('compile');
      void compileTypstSvg(source, { coalesce: true }, mainPath)
        .then((res) => {
          if (id !== runId.current) return;
          // A superseded compile did no work and carries no diagnostics:
          // adopting its empty result would blank the error banner a moment
          // before the real one arrives.
          if (res.superseded) return;
          setFatalError(null);
          switchTrace.mark('compiled');
          // Keep the last good render on error; never write into another document's state.
          setDoc((d) => (d.key !== docKey ? d : { ...d, diagnostics: res.diagnostics, svg: res.svg ?? d.svg }));
        })
        .catch((err) => {
          if (id !== runId.current) return;
          setFatalError(typstErrorMessage(err));
        })
        .finally(() => {
          if (id !== runId.current) return;
          setCompiling(false);
          setFirstLoad(false);
        });
    }, immediate ? 0 : DEBOUNCE_MS);

    return () => clearTimeout(timer);
  }, [source, revision, mainPath, docKey, ready]);

  // The pages of this render are in the DOM: restore the offset the user left
  // the document at (once), and close the switch trace.
  useLayoutEffect(() => {
    if (!svg) return;
    const el = pageAreaRef.current;
    if (el && shown.restoreScroll !== null) {
      el.scrollTop = shown.restoreScroll;
      scrollTopRef.current = shown.restoreScroll;
      setDoc((d) => (d.key === docKey ? { ...d, restoreScroll: null } : d));
    }
    const frame = requestAnimationFrame(() => switchTrace.mark('painted'));
    return () => cancelAnimationFrame(frame);
  }, [svg, docKey, shown.restoreScroll]);

  const errors = diagnostics.filter((d) => d.severity === 'error');

  // Per-page fragments (null: not a paged typst.ts document, mount as-is).
  // Recomputed only when the SVG changes; ~10 ms for a long report.
  const split: SplitTypstSvg | null = useMemo(() => splitTypstPages(svg), [svg]);
  const shared = useMemo(() => (split ? splitSharedStyle(split.shared) : null), [split]);

  // Text runs of each page, parsed from its fragment on demand: click-to-
  // source counts occurrences from the start of the document, and the pages
  // before the clicked one are usually not mounted. Lives with `split`, so a
  // new compile starts a fresh cache.
  const textRunCache = useMemo(() => new Map<number, string[]>(), [split]);
  const textRunsBefore = useCallback((pageIndex: number): string[] => {
    if (!split) return [];
    const out: string[] = [];
    for (let i = 0; i < pageIndex; i++) {
      let runs = textRunCache.get(i);
      if (!runs) { runs = extractTextRuns(split.pages[i]!.body); textRunCache.set(i, runs); }
      for (const run of runs) out.push(run);
    }
    return out;
  }, [split, textRunCache]);

  const onPageClick = useCallback((e: React.MouseEvent) => {
    if (!onRevealSource && !onRevealImage) return;
    // Let a text selection drag stay a selection rather than also jumping.
    if (window.getSelection()?.toString()) return;
    const host = pageAreaRef.current;
    if (!host) return;
    const card = split ? pageCardAt(host, e.target as Element | null, e.clientY) : null;
    const scope = card ?? host;
    if (onRevealImage) {
      const href = imageHrefAtPoint(scope, e.clientX, e.clientY);
      if (href) { onRevealImage(href); return; }
    }
    if (!onRevealSource) return;
    const preceding = card ? textRunsBefore(Number(card.dataset.pageIndex)) : [];
    const candidates = textRunAtPoint(scope, e.clientX, e.clientY, preceding);
    if (candidates.length > 0) onRevealSource(candidates);
  }, [onRevealSource, onRevealImage, split, textRunsBefore]);

  const zoomIn = useCallback(() => setZoom((z) => Math.min(MAX_ZOOM, +(z + 0.1).toFixed(2))), []);
  const zoomOut = useCallback(() => setZoom((z) => Math.max(MIN_ZOOM, +(z - 0.1).toFixed(2))), []);
  const resetZoom = useCallback(() => setZoom(1), []);

  return (
    <div className="flex h-full flex-col bg-[hsl(var(--muted)/0.35)]">
      {/* Toolbar */}
      <div className="flex h-8 shrink-0 items-center justify-between border-b border-[hsl(var(--border))] bg-[hsl(var(--card))] px-2">
        <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">
          {compiling ? (
            <>
              <Loader2 size={11} className="animate-spin" /> Rendering
            </>
          ) : errors.length > 0 ? (
            <span className="text-[hsl(var(--status-red))]">{errors.length} error{errors.length > 1 ? 's' : ''}</span>
          ) : (
            'Preview'
          )}
        </div>
        <div className="flex items-center gap-1">
          <button onClick={zoomOut} title="Zoom out" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <ZoomOut size={13} />
          </button>
          <button onClick={resetZoom} title="Reset zoom" className="min-w-[42px] rounded px-1 py-0.5 text-center font-mono text-[10px] hover:bg-[hsl(var(--accent))]">
            {Math.round(zoom * 100)}%
          </button>
          <button onClick={zoomIn} title="Zoom in" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <ZoomIn size={13} />
          </button>
          <button onClick={resetZoom} title="Fit width" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <Maximize size={13} />
          </button>
        </div>
      </div>

      {/* Error banner (overlaps the last good render) */}
      {fatalError ? (
        <div className="flex items-start gap-2 border-b border-[hsl(var(--status-red))]/40 bg-[hsl(var(--status-red))]/10 px-3 py-2 text-[11px] text-[hsl(var(--status-red))]">
          <AlertTriangle size={13} className="mt-0.5 shrink-0" />
          <span className="font-mono">{fatalError}</span>
        </div>
      ) : errors.length > 0 ? (
        <div className="max-h-32 shrink-0 overflow-y-auto border-b border-[hsl(var(--status-red))]/40 bg-[hsl(var(--status-red))]/10 px-3 py-2">
          {errors.map((d, i) => (
            <div key={i} className="flex items-start gap-2 text-[11px] text-[hsl(var(--status-red))]">
              <AlertTriangle size={12} className="mt-0.5 shrink-0" />
              <span className="font-mono">
                {(d.path || d.range) && (
                  <span className="opacity-70">{[d.path, d.range].filter(Boolean).join(':')}: </span>
                )}
                {d.message}
              </span>
            </div>
          ))}
        </div>
      ) : null}

      {/* Rendered document. `contain` isolates the page cards so resizing
          the pane doesn't relayout them beyond this box. */}
      <div
        ref={pageAreaRef}
        data-testid="preview-pages"
        onClick={onPageClick}
        onScroll={(e) => { scrollTopRef.current = e.currentTarget.scrollTop; }}
        title={onRevealSource ? 'Click the page to jump to that spot in the code' : undefined}
        className={`relative flex-1 overflow-auto p-6 ${onRevealSource ? 'cursor-pointer' : ''}`}
        style={{ contain: 'layout paint' }}
      >
        {firstLoad && !svg ? (
          <div className="flex h-full items-center justify-center text-center text-xs text-[hsl(var(--muted-foreground))]">
            <div className="flex flex-col items-center gap-2">
              <Loader2 size={18} className="animate-spin" />
              {ready ? 'Loading the Typst compiler…' : 'Opening…'}
              {ready && <span className="text-[10px] opacity-70">(first render initializes the local WASM engine)</span>}
            </div>
          </div>
        ) : !svg && (compiling || !ready) ? (
          // A document never rendered this session: nothing to show until the
          // compile lands, and the previous document's pages must not stand in.
          <div className="flex h-full items-center justify-center text-xs text-[hsl(var(--muted-foreground))]">
            <div className="flex flex-col items-center gap-2"><Loader2 size={18} className="animate-spin" />Rendering…</div>
          </div>
        ) : svg ? (
          // `will-change: transform` promotes the page stack to its own
          // layer, so zooming and pane-resizing composite instead of
          // repainting the document.
          <div
            className="mx-auto w-fit"
            style={{
              transform: `scale(${zoom})`,
              transformOrigin: 'top center',
              willChange: 'transform',
            }}
          >
            {/* SVG is produced by the local WASM compiler from the operator's own
                source (no remote input): consistent with the app's trusted-LAN
                threat model. */}
            {split && shared ? (
              <>
                <SharedStyle css={shared.css} />
                <SharedDefs markup={shared.defs} />
                <div className="flex flex-col items-center" style={{ gap: `${DEFAULT_PAGE_GAP}px` }}>
                  {split.pages.map((page, i) => (
                    <PageCard
                      key={i}
                      index={i}
                      tid={page.tid}
                      width={page.width}
                      height={page.height}
                      body={page.body}
                      scrollRoot={pageAreaRef}
                    />
                  ))}
                </div>
              </>
            ) : (
              // Not a paged typst.ts document: mount it whole on one card.
              <div
                className="rounded bg-white shadow-lg [&>svg]:block [&>svg]:h-auto [&>svg]:max-w-none"
                dangerouslySetInnerHTML={{ __html: svg }}
              />
            )}
          </div>
        ) : (
          <div className="flex h-full items-center justify-center text-xs text-[hsl(var(--muted-foreground))]">
            Nothing to render yet: start typing Typst on the left.
          </div>
        )}
      </div>
    </div>
  );
});
