// ─────────────────────────────────────────────────────────────────────────
// Live, locally-rendered Typst preview.
//
// Debounces the source, compiles it to SVG in-browser (see lib/typst-compiler)
// and shows the rendered page. Compile errors surface as a banner with the
// Typst diagnostics (file:line ranges) while the last good render stays
// visible, so a transient typo doesn't blank the preview.
// ─────────────────────────────────────────────────────────────────────────

import { useEffect, useRef, useState, useCallback, useMemo, memo } from 'react';
import { ZoomIn, ZoomOut, Maximize, Loader2, AlertTriangle } from 'lucide-react';
import { compileTypstSvg, typstErrorMessage, type TypstDiagnostic } from '@/lib/typst-compiler';
import { separateTypstPages } from '@/lib/typst-pages';
import { occurrenceIndex } from '@/lib/typst-source-map';

/** One guess at what a preview click corresponds to in the source. */
export interface SourceCandidate {
  text: string;
  occurrence: number;
}

/**
 * A rendered run that Typst generated rather than the author typing it:
 * a heading number, a figure counter. These have no source text to jump to,
 * so they're tried *after* their neighbours.
 *
 * Deliberately narrow: a short run of digits and dots. Real content that
 * looks numeric (an IP like `10.0.0.5`, a CVSS score in a table) stays a
 * first-class candidate.
 */
function looksAutoGenerated(text: string): boolean {
  return /^[\d.]{1,4}$/.test(text.trim());
}

/**
 * Resolve a click to ordered source candidates, best guess first.
 *
 * typst.ts emits a hidden selection layer: one `<foreignObject>` per text
 * run, containing a `.tsel` div with the literal characters. We hit-test
 * against those boxes geometrically rather than trusting `event.target`,
 * because the `.tsel` divs are `position: fixed` (typst.ts's trick for making
 * text selectable across the SVG), so whatever the browser reports as the
 * event target isn't reliably the run under the cursor.
 *
 * Falls back to the nearest box when the click lands in a margin or between
 * lines, so clicking roughly at something still works.
 */
function textRunAtPoint(
  container: HTMLElement,
  clientX: number,
  clientY: number,
): SourceCandidate[] {
  const objects = Array.from(container.querySelectorAll('foreignObject'));
  if (objects.length === 0) return [];

  const texts = objects.map((o) => o.textContent ?? '');

  let bestIndex = -1;
  let bestDistance = Infinity;
  for (let i = 0; i < objects.length; i++) {
    if (!texts[i]!.trim()) continue;
    const r = objects[i]!.getBoundingClientRect();
    if (r.width === 0 && r.height === 0) continue;

    // Distance to the box: zero when the point is inside it.
    const dx = Math.max(r.left - clientX, 0, clientX - r.right);
    const dy = Math.max(r.top - clientY, 0, clientY - r.bottom);
    const distance = Math.hypot(dx, dy);
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = i;
      if (distance === 0) break; // inside a run: can't do better
    }
  }

  if (bestIndex === -1) return [];
  // Ignore a click far from any text (empty page area) rather than yanking
  // the cursor to something arbitrary.
  if (bestDistance > 120) return [];

  // Offer the neighbours as fallbacks. Clicking a heading's number should
  // land on the heading, and a run whose text Typst transformed beyond
  // recognition shouldn't dead-end when the run beside it would resolve.
  const order = [bestIndex, bestIndex + 1, bestIndex - 1, bestIndex + 2];
  if (looksAutoGenerated(texts[bestIndex]!)) {
    // A counter has no source of its own: prefer the content it labels.
    order.splice(0, 1);
    order.push(bestIndex);
  }

  const seen = new Set<number>();
  const candidates: SourceCandidate[] = [];
  for (const i of order) {
    if (i < 0 || i >= texts.length || seen.has(i)) continue;
    seen.add(i);
    if (!texts[i]!.trim()) continue;
    candidates.push({ text: texts[i]!, occurrence: occurrenceIndex(texts, i) });
  }
  return candidates;
}

/** The data-URI href of the rendered image under the pointer, if any. */
function imageHrefAtPoint(
  container: HTMLElement,
  clientX: number,
  clientY: number,
): string | null {
  let best: { href: string; area: number } | null = null;
  for (const img of Array.from(container.querySelectorAll('svg image'))) {
    const r = img.getBoundingClientRect();
    if (clientX < r.left || clientX > r.right || clientY < r.top || clientY > r.bottom) continue;
    const href = img.getAttribute('href') || img.getAttribute('xlink:href');
    if (!href) continue;
    const area = r.width * r.height;
    // Prefer the smallest hit: a figure nested over a full-page background
    // image should win over the background.
    if (!best || area < best.area) best = { href, area };
  }
  return best?.href ?? null;
}

const DEBOUNCE_MS = 350;
const MIN_ZOOM = 0.25;
const MAX_ZOOM = 3;

// Memoized so it only re-renders when `source` (or the asset revision)
// actually changes: in particular it is skipped entirely while the user
// drags the editor/preview divider (which only changes the parent's width
// state).
//
// `revision` bumps whenever the workspace's images/fonts change. It isn't
// used in the render, only as a compile trigger: a crop or a new screenshot
// changes what the *same* source renders to.
export const TypstPreview = memo(function TypstPreview({
  source,
  revision = 0,
  mainPath = '/main.typ',
  onRevealSource,
  onRevealImage,
}: {
  source: string;
  revision?: number;
  /**
   * Where `source` is mounted in the compiler's virtual filesystem: the
   * workspace-relative path of the file open in the editor, so a document
   * that `#include`s its neighbours resolves them from the right directory.
   */
  mainPath?: string;
  /**
   * Click-to-source. Receives ordered candidates (best guess first, then
   * neighbouring runs); the handler takes the first that resolves.
   */
  onRevealSource?: (candidates: SourceCandidate[]) => void;
  /**
   * Click-to-asset: fires instead of click-to-source when the click lands
   * on a rendered image, with that `<image>`'s (data URI) href.
   */
  onRevealImage?: (href: string) => void;
}) {
  const [svg, setSvg] = useState<string>('');
  const [diagnostics, setDiagnostics] = useState<TypstDiagnostic[]>([]);
  const [fatalError, setFatalError] = useState<string | null>(null);
  const [firstLoad, setFirstLoad] = useState(true);
  const [compiling, setCompiling] = useState(false);
  const [zoom, setZoom] = useState(1);

  // Monotonic id so a slow compile that finishes after a newer one can't
  // overwrite the fresher result.
  const runId = useRef(0);

  useEffect(() => {
    const id = ++runId.current;
    setCompiling(true);
    const timer = setTimeout(() => {
      void compileTypstSvg(source, { coalesce: true }, mainPath)
        .then((res) => {
          if (id !== runId.current) return;
          // A superseded compile did no work and carries no diagnostics:
          // adopting its empty result would blank the error banner a moment
          // before the real one arrives.
          if (res.superseded) return;
          setFatalError(null);
          setDiagnostics(res.diagnostics);
          if (res.svg) setSvg(res.svg); // keep last good render on error
        })
        .catch((err) => {
          if (id !== runId.current) return;
          setFatalError(typstErrorMessage(err));
        })
        .finally(() => {
          if (id !== runId.current) return;
          setCompiling(false);
          setFirstLoad(false);
        });
    }, DEBOUNCE_MS);

    return () => clearTimeout(timer);
  }, [source, revision, mainPath]);

  const errors = diagnostics.filter((d) => d.severity === 'error');

  // Reflow the SVG so multi-page documents render as separated, white page
  // cards instead of one continuous sheet. Recomputed only when the SVG changes.
  const { svg: displaySvg, pages } = useMemo(() => separateTypstPages(svg), [svg]);

  const pageAreaRef = useRef<HTMLDivElement>(null);

  const onPageClick = useCallback((e: React.MouseEvent) => {
    if (!onRevealSource && !onRevealImage) return;
    // Let a text selection drag stay a selection rather than also jumping.
    if (window.getSelection()?.toString()) return;
    const host = pageAreaRef.current;
    if (!host) return;
    if (onRevealImage) {
      const href = imageHrefAtPoint(host, e.clientX, e.clientY);
      if (href) { onRevealImage(href); return; }
    }
    if (!onRevealSource) return;
    const candidates = textRunAtPoint(host, e.clientX, e.clientY);
    if (candidates.length > 0) onRevealSource(candidates);
  }, [onRevealSource, onRevealImage]);

  const zoomIn = useCallback(() => setZoom((z) => Math.min(MAX_ZOOM, +(z + 0.1).toFixed(2))), []);
  const zoomOut = useCallback(() => setZoom((z) => Math.max(MIN_ZOOM, +(z - 0.1).toFixed(2))), []);
  const resetZoom = useCallback(() => setZoom(1), []);

  return (
    <div className="flex h-full flex-col bg-[hsl(var(--muted)/0.35)]">
      {/* Toolbar */}
      <div className="flex h-8 shrink-0 items-center justify-between border-b border-[hsl(var(--border))] bg-[hsl(var(--card))] px-2">
        <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">
          {compiling ? (
            <>
              <Loader2 size={11} className="animate-spin" /> Rendering
            </>
          ) : errors.length > 0 ? (
            <span className="text-[hsl(var(--status-red))]">{errors.length} error{errors.length > 1 ? 's' : ''}</span>
          ) : (
            'Preview'
          )}
        </div>
        <div className="flex items-center gap-1">
          <button onClick={zoomOut} title="Zoom out" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <ZoomOut size={13} />
          </button>
          <button onClick={resetZoom} title="Reset zoom" className="min-w-[42px] rounded px-1 py-0.5 text-center font-mono text-[10px] hover:bg-[hsl(var(--accent))]">
            {Math.round(zoom * 100)}%
          </button>
          <button onClick={zoomIn} title="Zoom in" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <ZoomIn size={13} />
          </button>
          <button onClick={resetZoom} title="Fit width" className="rounded p-1 hover:bg-[hsl(var(--accent))]">
            <Maximize size={13} />
          </button>
        </div>
      </div>

      {/* Error banner (overlaps the last good render) */}
      {fatalError ? (
        <div className="flex items-start gap-2 border-b border-[hsl(var(--status-red))]/40 bg-[hsl(var(--status-red))]/10 px-3 py-2 text-[11px] text-[hsl(var(--status-red))]">
          <AlertTriangle size={13} className="mt-0.5 shrink-0" />
          <span className="font-mono">{fatalError}</span>
        </div>
      ) : errors.length > 0 ? (
        <div className="max-h-32 shrink-0 overflow-y-auto border-b border-[hsl(var(--status-red))]/40 bg-[hsl(var(--status-red))]/10 px-3 py-2">
          {errors.map((d, i) => (
            <div key={i} className="flex items-start gap-2 text-[11px] text-[hsl(var(--status-red))]">
              <AlertTriangle size={12} className="mt-0.5 shrink-0" />
              <span className="font-mono">
                {(d.path || d.range) && (
                  <span className="opacity-70">{[d.path, d.range].filter(Boolean).join(':')}: </span>
                )}
                {d.message}
              </span>
            </div>
          ))}
        </div>
      ) : null}

      {/* Rendered document. `contain` isolates the (potentially large) SVG
          subtree so resizing the pane doesn't relayout it beyond this box. */}
      <div
        ref={pageAreaRef}
        onClick={onPageClick}
        title={onRevealSource ? 'Click the page to jump to that spot in the code' : undefined}
        className={`relative flex-1 overflow-auto p-6 ${onRevealSource ? 'cursor-pointer' : ''}`}
        style={{ contain: 'layout paint' }}
      >
        {firstLoad && !svg ? (
          <div className="flex h-full items-center justify-center text-center text-xs text-[hsl(var(--muted-foreground))]">
            <div className="flex flex-col items-center gap-2">
              <Loader2 size={18} className="animate-spin" />
              Loading the Typst compiler…
              <span className="text-[10px] opacity-70">(first render initializes the local WASM engine)</span>
            </div>
          </div>
        ) : svg ? (
          // `will-change: transform` promotes the (often very large) page SVG
          // to its own layer, so zooming and pane-resizing composite instead
          // of repainting the whole document.
          <div
            className="mx-auto w-fit"
            style={{
              transform: `scale(${zoom})`,
              transformOrigin: 'top center',
              willChange: 'transform',
            }}
          >
            {/* SVG is produced by the local WASM compiler from the operator's own
                source (no remote input): consistent with the app's trusted-LAN
                threat model. When pages are recognized each gets its own white
                card (drawn into the SVG); otherwise fall back to a single card. */}
            {pages > 0 ? (
              <div
                className="[&>svg]:block [&>svg]:h-auto [&>svg]:max-w-none"
                dangerouslySetInnerHTML={{ __html: displaySvg }}
              />
            ) : (
              <div
                className="rounded bg-white shadow-lg [&>svg]:block [&>svg]:h-auto [&>svg]:max-w-none"
                dangerouslySetInnerHTML={{ __html: svg }}
              />
            )}
          </div>
        ) : (
          <div className="flex h-full items-center justify-center text-xs text-[hsl(var(--muted-foreground))]">
            Nothing to render yet: start typing Typst on the left.
          </div>
        )}
      </div>
    </div>
  );
});
